theme = "tokyonight"
client_id = "86dc052a6f3d45329fc98aa9f3dfb888"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Thick"
progress_bar_type = "Rectangle"
enable_media_control = false
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "spotify-player"
seek_duration_secs = 5

[layout]
playback_window_position = "Bottom"
playback_window_height = 6


[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
